# General Fake TLS Auto ALT Strategy
# Использует fake+fakedsplit с badseq fooling
id: "zapret_general_fake_tls_auto_alt"
name: "Fake TLS Auto ALT"
description: "Fake+fakedsplit с badseq fooling и автогенерацией TLS. Эффективен для провайдеров с базовым DPI."
family: fake
engine: zapret
label: autottl

mode_capabilities:
  supports_socks: false
  supports_global: true

global_template:
  binary: "binaries/winws.exe"
  args:
    # WinDivert фильтры
    - "--wf-tcp=80,443,2053,2083,2087,2096,8443"
    - "--wf-udp=443,19294-19344,50000-50100"
    # QUIC fake для общего списка
    - "--filter-udp=443"
    - "--hostlist=hostlists/general.txt"
    - "--hostlist-exclude=hostlists/exclude.txt"
    - "--ipset-exclude=hostlists/ipset-exclude.txt"
    - "--dpi-desync=fake"
    - "--dpi-desync-repeats=11"
    - "--dpi-desync-fake-quic=binaries/quic_initial_www_google_com.bin"
    - "--new"
    # Discord voice/STUN
    - "--filter-udp=19294-19344,50000-50100"
    - "--filter-l7=discord,stun"
    - "--dpi-desync=fake"
    - "--dpi-desync-fake-discord=binaries/quic_initial_www_google_com.bin"
    - "--dpi-desync-fake-stun=binaries/quic_initial_www_google_com.bin"
    - "--dpi-desync-repeats=6"
    - "--new"
    # Discord media CDN с fakedsplit
    - "--filter-tcp=2053,2083,2087,2096,8443"
    - "--hostlist-domains=discord.media"
    - "--dpi-desync=fake,fakedsplit"
    - "--dpi-desync-split-pos=1"
    - "--dpi-desync-fooling=badseq"
    - "--dpi-desync-badseq-increment=2"
    - "--dpi-desync-repeats=8"
    - "--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
    - "--new"
    # Google/YouTube с fakedsplit
    - "--filter-tcp=443"
    - "--hostlist=hostlists/google.txt"
    - "--ip-id=zero"
    - "--dpi-desync=fake,fakedsplit"
    - "--dpi-desync-split-pos=1"
    - "--dpi-desync-fooling=badseq"
    - "--dpi-desync-badseq-increment=2"
    - "--dpi-desync-repeats=8"
    - "--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
    - "--new"
    # TCP fake+fakedsplit для общего списка
    - "--filter-tcp=80,443"
    - "--hostlist=hostlists/general.txt"
    - "--hostlist-exclude=hostlists/exclude.txt"
    - "--ipset-exclude=hostlists/ipset-exclude.txt"
    - "--dpi-desync=fake,fakedsplit"
    - "--dpi-desync-split-pos=1"
    - "--dpi-desync-fooling=badseq"
    - "--dpi-desync-badseq-increment=2"
    - "--dpi-desync-repeats=8"
    - "--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
    - "--new"
    # QUIC для ipset
    - "--filter-udp=443"
    - "--ipset=hostlists/ipset-all.txt"
    - "--hostlist-exclude=hostlists/exclude.txt"
    - "--ipset-exclude=hostlists/ipset-exclude.txt"
    - "--dpi-desync=fake"
    - "--dpi-desync-repeats=11"
    - "--dpi-desync-fake-quic=binaries/quic_initial_www_google_com.bin"
    - "--new"
    # TCP для ipset с fakedsplit
    - "--filter-tcp=80,443"
    - "--ipset=hostlists/ipset-all.txt"
    - "--hostlist-exclude=hostlists/exclude.txt"
    - "--ipset-exclude=hostlists/ipset-exclude.txt"
    - "--dpi-desync=fake,fakedsplit"
    - "--dpi-desync-split-pos=1"
    - "--dpi-desync-fooling=badseq"
    - "--dpi-desync-badseq-increment=2"
    - "--dpi-desync-repeats=8"
    - "--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
  env: {}
  requires_admin: true

requirements:
  min_rights: "admin"
  os:
    - windows
  binaries:
    - "binaries/winws.exe"
    - "binaries/WinDivert64.sys"
    - "binaries/quic_initial_www_google_com.bin"

weight_hint: 10
services:
  - discord
  - youtube
  - general
