# Билайн Provider Profile
id: beeline
name: Билайн
description: Мобильный и домашний интернет
dpi_type: ТСПУ + EcoDPI
regions:
  - Москва
  - Санкт-Петербург
  - Все регионы России

recommended_strategies:
  - zapret_general_multisplit      # Первый приоритет
  - zapret_general_fake_tls        # Альтернатива
  - zapret_general_alt4            # Для Билайн часто работает
  - zapret_general_simple_fake     # Простая стратегия

notes: |
  Билайн использует ТСПУ в сочетании с EcoDPI.
  
  Рекомендации:
  1. Multisplit обычно работает хорошо
  2. При проблемах попробуйте alt4 - специфично для Билайн
  3. Simple fake может работать на домашнем интернете
  
  Особенности:
  - Домашний интернет обычно менее заблокирован
  - Мобильная сеть может требовать более агрессивные стратегии
  - QUIC блокируется частично
